### ISSUE TITLE
todo list for client

### ISSUE THREAD

**Issue by boomik305** [boomik305/kuber#1]
###### Formatting
> - [x] ```Work with problems``` 
> - [ ] ``` Developing paused ```
- [x] ``` Stable work ```
- [ ] ``` Developing in progress  ```

###### Todo
- [ ]  Tabs API

> - [ ]  Extension API and Extension Manager

- [ ] Local FileSystem with saving to LocalStorage or IndexedDB

- [ ] Support [UTF-C](https://github.com/deNULL/utf-c) compact utf-8

> - [ ] Themes support

- [ ] Support monaco-editor or codemirror
